[build-system]
requires = ["setuptools>=64.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "base4"
version = "0.1.0"
description = "Internal backend devl library"
authors = [
    { name = "Digital CUBE", email = "info@digitalcube.rs" }
]
readme = "README.md"
requires-python = ">=3.12.6"
dependencies = [
	# GENERATED ON: 2024-11-20 21:16:13
	'redis==5.2.0',
	'python-multipart==0.0.17', #0.0.12
	'cryptography==43.0.3',
	'pytest-asyncio==0.24.0',
	'python-slugify==8.0.4', #8.0.1
	'Jinja2==3.1.4',
	'python-dotenv==1.0.1',
	'black==24.10.0',
	'fastapi==0.115.5', #0.115.4
	'asyncpg==0.30.0',
	'isort==5.13.2',
	'setuptools==75.6.0', #75.3.0
	'PyJWT==2.10.0',
	'python-socketio==5.11.4',
	'GitPython==3.1.43',
	'aiofiles==24.1.0',
	'lark-parser==0.12.0',
	'httpx==0.27.2',
	'PyYAML==6.0.2',
	'pytest-xdist==3.6.1',
	'pydash==8.0.4', #8.0.3
	'asyncclick==8.1.7.2',
	'fakeredis==2.26.1',
	'tortoise-orm==0.22.0', #0.21.7
	'aerich==0.7.2',
	'bcrypt==4.2.1', #4.2.0
	'pytest==8.3.3',
	'Unidecode==1.3.8',
	'uvicorn==0.32.1', #0.32.0
	'pytest-cov==6.0.0',
	'ujson==5.10.0',
	'requests==2.26.0',

]

[project.urls]
repository = "https://github.com/digital-cube/base4"

[tool.setuptools.package-data]
"base4" = ["*.json"]

[project.scripts]
    bmanager = "base4.scripts.bmanager:do"
    testall = "base4.scripts.testall:do"

[tool.setuptools]
packages = [
    "base4",
    'base4.scripts',
    'base4.scripts.pip',
    "base4.schemas",
    "base4.models",
    "base4.service",
    "base4.api",
    'base4.utilities',
    'base4.constants.users',
    'base4.constants.service',
    'base4.utilities.logging',
    'base4.utilities.db',
    'base4.utilities.http',
    'base4.utilities.parsers',
    'base4.utilities.security',
    'base4.utilities.service',
    'base4.ws',
]
